<?php
/*
 * NetScanner package privileges
 */

$priv_list['page-services-netscanner'] = array();
$priv_list['page-services-netscanner']['name'] = gettext("NetScanner: Status");
$priv_list['page-services-netscanner']['descr'] = gettext("Allow access to NetScanner status page");
$priv_list['page-services-netscanner']['warn'] = "standard";

$priv_list['page-services-netscanner-settings'] = array();
$priv_list['page-services-netscanner-settings']['name'] = gettext("NetScanner: Settings");
$priv_list['page-services-netscanner-settings']['descr'] = gettext("Allow access to NetScanner settings");
$priv_list['page-services-netscanner-settings']['warn'] = "standard";

?>
