#!/bin/sh
# Install NetScanner BRIDGE-MIB helper on an OpenWrt DSA switch.
# Run AS ROOT on the switch, from a directory that already contains:
#   netscanner-bridge-mib.py
#   snmpd.netscanner.conf
#
# Example from your workstation (replace SWITCH):
#   scp integrations/openwrt/netscanner-bridge-mib.py \
#       integrations/openwrt/snmpd.netscanner.conf \
#       integrations/openwrt/install-bridge-mib.sh \
#       root@SWITCH:/tmp/
#   ssh root@SWITCH 'sh /tmp/install-bridge-mib.sh'
set -eu

BRIDGE="${NETSCANNER_BRIDGE:-br-lan}"
SCRIPT_SRC="$(cd "$(dirname "$0")" && pwd)/netscanner-bridge-mib.py"
DEST=/usr/bin/netscanner-bridge-mib
RO_COMMUNITY="${NETSCANNER_SNMP_COMMUNITY:-public}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root on the OpenWrt switch" >&2
  exit 1
fi

if [ ! -f "$SCRIPT_SRC" ]; then
  echo "Missing $SCRIPT_SRC" >&2
  exit 1
fi

echo "==> Packages"
opkg update || true
opkg install snmpd python3 2>/dev/null || true
opkg install ip-bridge 2>/dev/null || opkg install bridge 2>/dev/null || opkg install ip-full 2>/dev/null || true

if ! command -v python3 >/dev/null; then
  echo "python3 not found — install python3 via opkg" >&2
  exit 1
fi
if ! command -v bridge >/dev/null; then
  echo "bridge(8) not found — install ip-bridge / bridge / ip-full" >&2
  exit 1
fi

echo "==> Install $DEST"
# BusyBox may lack `install -m`; use cp + chmod
cp "$SCRIPT_SRC" "$DEST"
chmod 0755 "$DEST"

if [ ! -d "/sys/class/net/$BRIDGE" ]; then
  echo "WARNING: bridge $BRIDGE not found. Set NETSCANNER_BRIDGE=… or edit the script." >&2
fi

CONF=
for candidate in /etc/snmp/snmpd.conf /var/run/snmpd.conf /tmp/snmpd.conf; do
  if [ -f "$candidate" ]; then
    CONF=$candidate
    break
  fi
done

# Prefer durable drop-in if present
mkdir -p /etc/snmp
DROPIN=/etc/snmp/snmpd_netscanner.conf
cat > "$DROPIN" <<EOF
# Generated by NetScanner install-bridge-mib.sh
# Set NETSCANNER_SNMP_COMMUNITY before install to override (default: public).
rocommunity ${RO_COMMUNITY} default
pass_persist .1.3.6.1.2.1.17 $DEST
EOF

if [ -n "$CONF" ]; then
  echo "==> Patching $CONF"
  cp "$CONF" "${CONF}.bak.$(date +%s)" 2>/dev/null || true
  if grep -q 'pass_persist .1.3.6.1.2.1.17' "$CONF" 2>/dev/null; then
    echo "pass_persist already present in $CONF"
  else
    printf '\n# --- NetScanner BRIDGE-MIB ---\nincludeFile %s\n' "$DROPIN" >> "$CONF" 2>/dev/null \
      || cat "$DROPIN" >> "$CONF"
  fi
else
  echo "==> No snmpd.conf found; wrote $DROPIN — include it from your package config"
fi

# UCI note: many OpenWrt builds regenerate snmpd.conf. Try appending via procd include.
if [ -f /etc/config/snmpd ]; then
  echo "==> /etc/config/snmpd exists — ensure pass_persist survives restarts (see README)"
fi

echo "==> Restart snmpd"
/etc/init.d/snmpd enable 2>/dev/null || true
/etc/init.d/snmpd restart || snmpd -c "$CONF" || true
sleep 1

echo "==> Local check"
if command -v snmpwalk >/dev/null; then
  snmpwalk -v2c -c "${RO_COMMUNITY}" -t 2 127.0.0.1 1.3.6.1.2.1.17.4.3.1.1 2>&1 | head -10 \
    || echo "(install snmp-utils for local walk, or test from your workstation)"
else
  echo "Install snmp-utils for local verification, or run from your workstation:"
  echo "  snmpwalk -v2c -c ${RO_COMMUNITY} SWITCH 1.3.6.1.2.1.17.4.3.1.1"
fi

echo "Done. bridge=$BRIDGE script=$DEST dropin=$DROPIN community=${RO_COMMUNITY}"
