/** Shared mDNS/Bonjour service types for scan probes and passive listeners. */
export const MDNS_SERVICE_TYPES = [
  'http',
  'https',
  'ipp',
  'printer',
  'pdl-datastream',
  'airplay',
  'raop',
  'googlecast',
  'spotify-connect',
  'hap',
  'ssh',
  'smb',
  'afpovertcp',
  'workstation',
  'homekit',
  'sonos',
  'companion-link',
  'sleep-proxy',
  'device-info',
  'airdrop',
  'apple-mobdev2',
  'androidtvremote2',
  'daap',
  'sftp-ssh',
  'nfs',
  'plex',
  'hue',
  'tuya',
  'esphomelib',
  'matter',
] as const;
